2025-03-14 00:05:02,001 - Default - MainProcess - 33573 - aliyun-deepseek-r1-M3: starts for Task ID: 9
2025-03-14 00:05:59,929 - Default - MainProcess - 33573 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 274, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 210, in main
    if not x:
           ^
NameError: name 'x' is not defined
!!!
----------------------

2025-03-14 00:06:45,475 - Default - MainProcess - 33573 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.467
----------------------

2025-03-14 00:06:46,082 - Default - MainProcess - 33573 - aliyun-deepseek-r1-M3: completed for Task ID: 9, LLM Time: 54.70s
2025-03-14 00:06:46,187 - Default - MainProcess - 33573 - aliyun-deepseek-r1-M3: starts for Task ID: 10
2025-03-14 00:08:01,908 - Default - MainProcess - 34986 - aliyun-deepseek-r1-M3: starts for Task ID: 1
2025-03-14 00:08:46,843 - Default - MainProcess - 34986 - Count 0:
codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211
    posCommand = Motion_PosCommand()
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 00:11:23,866 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 1
2025-03-14 00:12:15,255 - Default - MainProcess - 36539 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.797
----------------------

2025-03-14 00:12:15,813 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 1, LLM Time: 47.48s
2025-03-14 00:12:15,916 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 2
2025-03-14 00:13:00,229 - Default - MainProcess - 36539 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.353
----------------------

2025-03-14 00:13:00,619 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 2, LLM Time: 40.85s
2025-03-14 00:13:00,721 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 3
2025-03-14 00:14:48,824 - Default - MainProcess - 36539 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.679
----------------------

2025-03-14 00:14:49,240 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 3, LLM Time: 104.31s
2025-03-14 00:14:49,343 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 4
2025-03-14 00:16:25,049 - Default - MainProcess - 36539 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 271, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 210, in main
    if XYZ == 0:
       ^^^
NameError: name 'XYZ' is not defined
!!!
----------------------

2025-03-14 00:17:51,547 - Default - MainProcess - 36539 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.180
----------------------

2025-03-14 00:17:51,954 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 4, LLM Time: 92.74s
2025-03-14 00:17:52,056 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 5
2025-03-14 00:20:03,282 - Default - MainProcess - 36539 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.743
----------------------

2025-03-14 00:20:03,713 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 5, LLM Time: 126.35s
2025-03-14 00:20:03,814 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 6
2025-03-14 00:21:05,417 - Default - MainProcess - 36539 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.515
----------------------

2025-03-14 00:21:05,901 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 6, LLM Time: 57.98s
2025-03-14 00:21:06,002 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 7
2025-03-14 00:24:11,343 - Default - MainProcess - 36539 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.555
----------------------

2025-03-14 00:24:11,756 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: completed for Task ID: 7, LLM Time: 181.68s
2025-03-14 00:24:11,856 - Default - MainProcess - 36539 - aliyun-deepseek-r1-M3: starts for Task ID: 8
2025-03-14 00:31:13,490 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: starts for Task ID: 8
2025-03-14 00:33:23,895 - Default - MainProcess - 43067 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.506
----------------------

2025-03-14 00:33:24,450 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: completed for Task ID: 8, LLM Time: 125.79s
2025-03-14 00:33:24,551 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: starts for Task ID: 9
2025-03-14 00:34:10,920 - Default - MainProcess - 43067 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 275, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211, in main
    if not x:
           ^
NameError: name 'x' is not defined
!!!
----------------------

2025-03-14 00:35:43,773 - Default - MainProcess - 43067 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.071
----------------------

2025-03-14 00:35:44,061 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: completed for Task ID: 9, LLM Time: 43.09s
2025-03-14 00:35:44,162 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: starts for Task ID: 10
2025-03-14 00:36:53,630 - Default - MainProcess - 43067 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.438
----------------------

2025-03-14 00:36:54,048 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: completed for Task ID: 10, LLM Time: 65.92s
2025-03-14 00:36:54,150 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: starts for Task ID: 11
2025-03-14 00:39:29,626 - Default - MainProcess - 43067 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.368
----------------------

2025-03-14 00:39:30,037 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: completed for Task ID: 11, LLM Time: 151.00s
2025-03-14 00:39:30,140 - Default - MainProcess - 43067 - aliyun-deepseek-r1-M3: starts for Task ID: 12
2025-03-14 00:40:15,626 - Default - MainProcess - 43067 - Count 0:
codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 210
    jogCommand = Motion_JogCommand()
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 01:01:19,231 - Default - MainProcess - 47924 - aliyun-deepseek-r1-M3: starts for Task ID: 12
2025-03-14 11:14:25,160 - Default - MainProcess - 10637 - DeepSeek-R1-M3: starts for Task ID: 67
2025-03-14 11:22:40,166 - Default - MainProcess - 10637 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 10.783
----------------------

2025-03-14 11:22:40,938 - Default - MainProcess - 10637 - DeepSeek-R1-M3: completed for Task ID: 67, LLM Time: 484.11s
2025-03-14 11:22:41,040 - Default - MainProcess - 10637 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 11:27:28,311 - Default - MainProcess - 10637 - Count 1:
codedata:
Program begin.
AddPathIntplWithRotationCommand error code is 65581: [0x0001002d] : CoreMotionApi Error: One or more velocity arguments out of range.
Elapsed_time: 4.658
----------------------

2025-03-14 11:41:47,882 - Default - MainProcess - 19924 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 11:45:27,952 - Default - MainProcess - 19924 - Count 1:
codedata:
Program begin.
AddPathIntplWithRotationCommand error code is 65581: [0x0001002d] : CoreMotionApi Error: One or more velocity arguments out of range.
Elapsed_time: 3.035
----------------------

2025-03-14 11:58:47,768 - Default - MainProcess - 25305 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:01:09,053 - Default - MainProcess - 26039 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:02:35,330 - Default - MainProcess - 26530 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:03:44,315 - Default - MainProcess - 26928 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:05:33,905 - Default - MainProcess - 27551 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:06:29,447 - Default - MainProcess - 28704 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:08:27,936 - Default - MainProcess - 29347 - DeepSeek-R1-M3: starts for Task ID: 68
2025-03-14 12:14:10,575 - Default - MainProcess - 29347 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 9.194
----------------------

2025-03-14 12:14:11,260 - Default - MainProcess - 29347 - DeepSeek-R1-M3: completed for Task ID: 68, LLM Time: 333.33s
2025-03-14 12:14:11,364 - Default - MainProcess - 29347 - DeepSeek-R1-M3: starts for Task ID: 69
2025-03-14 12:19:17,240 - Default - MainProcess - 32767 - DeepSeek-R1-M3: starts for Task ID: 69
2025-03-14 12:23:38,365 - Default - MainProcess - 32767 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 9.075
----------------------

2025-03-14 12:23:39,057 - Default - MainProcess - 32767 - DeepSeek-R1-M3: completed for Task ID: 69, LLM Time: 251.93s
2025-03-14 12:23:39,161 - Default - MainProcess - 32767 - DeepSeek-R1-M3: starts for Task ID: 70
2025-03-14 12:32:15,938 - Default - MainProcess - 32767 - Count 1:
codedata:
Program begin.
PathIntplLookahead Running timeout!
Elapsed_time: 58.409
----------------------

2025-03-14 12:32:16,625 - Default - MainProcess - 32767 - DeepSeek-R1-M3: completed for Task ID: 70, LLM Time: 458.22s
2025-03-14 12:32:16,728 - Default - MainProcess - 32767 - DeepSeek-R1-M3: starts for Task ID: 71
2025-03-14 13:15:58,030 - Default - MainProcess - 50025 - DeepSeek-R1-M3: starts for Task ID: 70
2025-03-14 13:18:48,551 - Default - MainProcess - 50962 - DeepSeek-R1-M3: starts for Task ID: 70
2025-03-14 13:32:41,231 - Default - MainProcess - 55176 - DeepSeek-R1-M3: starts for Task ID: 70
2025-03-14 13:54:00,752 - Default - MainProcess - 61791 - DeepSeek-R1-M3: starts for Task ID: 70
2025-03-14 14:03:10,154 - Default - MainProcess - 64793 - DeepSeek-R1-M1: starts for Task ID: 1
2025-03-14 14:03:49,095 - Default - MainProcess - 64793 - codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211
    posCommand = Motion_PosCommand()
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 14:03:49,201 - Default - MainProcess - 64793 - DeepSeek-R1-M1 Error detected for Task ID: 1
2025-03-14 14:03:49,201 - Default - MainProcess - 64793 - DeepSeek-R1-M1: completed for Task ID: 1, LLM Time: 37.75s
2025-03-14 14:03:49,307 - Default - MainProcess - 64793 - DeepSeek-R1-M1: starts for Task ID: 2
2025-03-14 14:04:39,099 - Default - MainProcess - 65361 - DeepSeek-R1-M1: starts for Task ID: 1
2025-03-14 14:05:57,754 - Default - MainProcess - 65361 - codedata:
Program begin.
Program End.
Elapsed_time: 3.726
----------------------

2025-03-14 14:05:58,348 - Default - MainProcess - 65361 - DeepSeek-R1-M1: completed for Task ID: 1, LLM Time: 74.82s
2025-03-14 14:05:58,451 - Default - MainProcess - 65361 - DeepSeek-R1-M1: starts for Task ID: 2
2025-03-14 14:23:07,135 - Default - MainProcess - 71298 - DeepSeek-R1-M1: starts for Task ID: 1
2025-03-14 14:24:06,568 - Default - MainProcess - 71298 - codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211
    posCommand = Motion_PosCommand()
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 14:24:07,133 - Default - MainProcess - 71298 - DeepSeek-R1-M1 Error detected for Task ID: 1
2025-03-14 14:24:07,133 - Default - MainProcess - 71298 - DeepSeek-R1-M1: completed for Task ID: 1, LLM Time: 58.25s
2025-03-14 14:24:07,236 - Default - MainProcess - 71298 - DeepSeek-R1-M1: starts for Task ID: 2
2025-03-14 14:25:08,030 - Default - MainProcess - 71298 - codedata:
Program begin.
Program End.
Elapsed_time: 3.584
----------------------

2025-03-14 14:25:08,441 - Default - MainProcess - 71298 - DeepSeek-R1-M1: completed for Task ID: 2, LLM Time: 57.10s
2025-03-14 14:25:08,542 - Default - MainProcess - 71298 - DeepSeek-R1-M1: starts for Task ID: 3
2025-03-14 14:34:07,609 - Default - MainProcess - 74895 - o3-mini-M3: starts for Task ID: 4
2025-03-14 14:34:37,167 - Default - MainProcess - 74895 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 286, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211, in main
    if XYZ == 0:
       ^^^
NameError: name 'XYZ' is not defined
!!!
----------------------

2025-03-14 14:34:50,643 - Default - MainProcess - 74895 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 3.098
----------------------

2025-03-14 14:34:51,072 - Default - MainProcess - 74895 - o3-mini-M3: completed for Task ID: 4, LLM Time: 26.34s
2025-03-14 14:36:46,199 - Default - MainProcess - 75755 - o3-mini-M3: starts for Task ID: 4
2025-03-14 14:37:07,237 - Default - MainProcess - 75755 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 276, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211, in main
    if XYZ == 0:
       ^^^
NameError: name 'XYZ' is not defined
!!!
----------------------

2025-03-14 14:37:22,257 - Default - MainProcess - 75755 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 3.221
----------------------

2025-03-14 14:37:22,798 - Default - MainProcess - 75755 - o3-mini-M3: completed for Task ID: 4, LLM Time: 17.96s
2025-03-14 14:38:42,901 - Default - MainProcess - 76378 - o3-mini-M3: starts for Task ID: 14
2025-03-14 14:39:02,466 - Default - MainProcess - 76378 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 276, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 214, in main
    jogCommand.profile.type = ProfileType.TimeaccTrapezoidal  # Use the TimeaccTrapezoidal profile
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'TimeaccTrapezoidal'. Did you mean: 'TimeAccTrapezoidal'?
!!!
----------------------

2025-03-14 14:39:13,816 - Default - MainProcess - 76378 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 2.963
----------------------

2025-03-14 14:39:14,397 - Default - MainProcess - 76378 - o3-mini-M3: completed for Task ID: 14, LLM Time: 16.41s
2025-03-14 14:41:39,756 - Default - MainProcess - 77337 - CanonicalCode: starts for Task ID: 16
2025-03-14 14:41:56,222 - Default - MainProcess - 77337 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 300, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 244, in main
    ret = Wmx3Lib_adv.advMotion.StartPathIntplPos(path)
          ^^^^^^^^^^^
NameError: name 'Wmx3Lib_adv' is not defined. Did you mean: 'Wmx3Lib_cm'?
!!!
----------------------

2025-03-14 14:42:16,672 - Default - MainProcess - 77337 - Count 2:
codeerr:
!!!
----------------------

2025-03-14 14:42:16,673 - Default - MainProcess - 77337 - CanonicalCode Error detected for Task ID: 16
2025-03-14 14:42:16,673 - Default - MainProcess - 77337 - CanonicalCode: completed for Task ID: 16, LLM Time: 12.85s
2025-03-14 14:42:16,777 - Default - MainProcess - 77337 - CanonicalCode: starts for Task ID: 17
2025-03-14 14:42:29,843 - Default - MainProcess - 77337 - Count 1:
codedata:
Program begin.
StartLinearIntplMov error code is 1563: [0x0000061b] : WMX3Api Error: The axis is still starting the previous command. Wait until the next communication cycle.
Elapsed_time: 3.727
----------------------

2025-03-14 14:42:48,682 - Default - MainProcess - 77337 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 3.626
----------------------

2025-03-14 14:42:49,286 - Default - MainProcess - 77337 - CanonicalCode: completed for Task ID: 17, LLM Time: 9.23s
2025-03-14 14:43:06,523 - Default - MainProcess - 77817 - CanonicalCode: starts for Task ID: 16
2025-03-14 14:43:24,315 - Default - MainProcess - 77817 - Count 1:
codeerr:
!!!
----------------------

2025-03-14 14:43:44,674 - Default - MainProcess - 77817 - Count 2:
codeerr:
!!!
----------------------

2025-03-14 14:43:44,675 - Default - MainProcess - 77817 - CanonicalCode Error detected for Task ID: 16
2025-03-14 14:43:44,675 - Default - MainProcess - 77817 - CanonicalCode: completed for Task ID: 16, LLM Time: 12.89s
2025-03-14 14:44:05,948 - Default - MainProcess - 78180 - CanonicalCode: starts for Task ID: 16
2025-03-14 14:45:04,240 - Default - MainProcess - 78180 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.711
----------------------

2025-03-14 14:45:04,803 - Default - MainProcess - 78180 - CanonicalCode: completed for Task ID: 16, LLM Time: 54.47s
2025-03-14 14:47:12,811 - Default - MainProcess - 79277 - CanonicalCode: starts for Task ID: 33
2025-03-14 14:47:34,254 - Default - MainProcess - 79277 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.639
----------------------

2025-03-14 14:47:34,883 - Default - MainProcess - 79277 - CanonicalCode: completed for Task ID: 33, LLM Time: 15.67s
2025-03-14 14:48:59,044 - Default - MainProcess - 79932 - o3-mini-M3: starts for Task ID: 43
2025-03-14 14:50:02,154 - Default - MainProcess - 80276 - o3-mini-M3: starts for Task ID: 43
2025-03-14 14:50:50,899 - Default - MainProcess - 80276 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.040
----------------------

2025-03-14 14:50:51,468 - Default - MainProcess - 80276 - o3-mini-M3: completed for Task ID: 43, LLM Time: 43.59s
2025-03-14 14:53:26,270 - Default - MainProcess - 81339 - CanonicalCode: starts for Task ID: 59
2025-03-14 14:54:50,442 - Default - MainProcess - 81798 - CanonicalCode: starts for Task ID: 59
2025-03-14 14:57:16,101 - Default - MainProcess - 82604 - CanonicalCode: starts for Task ID: 59
2025-03-14 14:59:08,575 - Default - MainProcess - 83290 - CanonicalCode: starts for Task ID: 59
2025-03-14 14:59:56,875 - Default - MainProcess - 83290 - Count 1:
codedata:
Program begin.
FreeSplineBuffer error code is 65627: [0x0001005b] : CoreMotionApi Error: Channel buffer memory has not been allocated.
Program End.
Elapsed_time: 4.942
----------------------

2025-03-14 15:00:32,077 - Default - MainProcess - 83290 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 4.627
----------------------

2025-03-14 15:00:32,664 - Default - MainProcess - 83290 - CanonicalCode: completed for Task ID: 59, LLM Time: 43.23s
2025-03-14 15:04:21,245 - Default - MainProcess - 84987 - CanonicalCode: starts for Task ID: 65
2025-03-14 15:05:12,913 - Default - MainProcess - 84987 - Count 1:
codedata:
Program begin.
FreePathIntplWithRotationBuffer error code is 65627: [0x0001005b] : CoreMotionApi Error: Channel buffer memory has not been allocated.
Elapsed_time: 4.201
----------------------

2025-03-14 15:05:59,007 - Default - MainProcess - 84987 - Count 2:

2025-03-14 15:05:59,577 - Default - MainProcess - 84987 - CanonicalCode: completed for Task ID: 65, LLM Time: 47.35s
2025-03-14 15:07:02,196 - Default - MainProcess - 85925 - CanonicalCode: starts for Task ID: 65
2025-03-14 15:08:08,017 - Default - MainProcess - 86348 - CanonicalCode: starts for Task ID: 65
2025-03-14 15:09:27,496 - Default - MainProcess - 86812 - CanonicalCode: starts for Task ID: 65
2025-03-14 15:11:22,023 - Default - MainProcess - 87456 - CanonicalCode: starts for Task ID: 65
2025-03-14 15:12:01,959 - Default - MainProcess - 87456 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 398, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 20, in main
    sleep(0.1)
    ^^^^^
UnboundLocalError: cannot access local variable 'sleep' where it is not associated with a value
!!!
----------------------

2025-03-14 15:12:25,519 - Default - MainProcess - 87456 - Count 2:
codedata:
Program begin.
FreePathIntplWithRotationBuffer error code: 65627
Elapsed_time: 3.928
----------------------

2025-03-14 15:12:25,520 - Default - MainProcess - 87456 - CanonicalCode Error detected for Task ID: 65
2025-03-14 15:12:25,520 - Default - MainProcess - 87456 - CanonicalCode: completed for Task ID: 65, LLM Time: 38.67s
2025-03-14 15:12:41,327 - Default - MainProcess - 87883 - CanonicalCode: starts for Task ID: 65
2025-03-14 15:13:22,707 - Default - MainProcess - 87883 - Count 1:
codedata:
Program begin.
FreePathIntplWithRotationBuffer error code: 65627 [0x0001005b] : CoreMotionApi Error: Channel buffer memory has not been allocated.
Program End.
Elapsed_time: 3.165
----------------------

2025-03-14 15:13:48,047 - Default - MainProcess - 87883 - Count 2:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x93' in file \\mac\Home\Downloads\codedemo\sample.py on line 217, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 15:13:48,048 - Default - MainProcess - 87883 - CanonicalCode Error detected for Task ID: 65
2025-03-14 15:13:48,048 - Default - MainProcess - 87883 - CanonicalCode: completed for Task ID: 65, LLM Time: 38.11s
2025-03-14 15:19:51,649 - Default - MainProcess - 90134 - CanonicalCode: starts for Task ID: 75
2025-03-14 15:20:13,669 - Default - MainProcess - 90134 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.849
----------------------

2025-03-14 15:20:14,270 - Default - MainProcess - 90134 - CanonicalCode: completed for Task ID: 75, LLM Time: 17.06s
2025-03-14 15:20:43,461 - Default - MainProcess - 90427 - gpt-4o-M3: starts for Task ID: 75
2025-03-14 15:21:07,312 - Default - MainProcess - 90427 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.696
----------------------

2025-03-14 15:21:07,930 - Default - MainProcess - 90427 - gpt-4o-M3: completed for Task ID: 75, LLM Time: 19.04s
2025-03-14 15:21:36,667 - Default - MainProcess - 90744 - gpt-4o-M3: starts for Task ID: 76
2025-03-14 15:22:01,918 - Default - MainProcess - 90744 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.486
----------------------

2025-03-14 15:22:02,539 - Default - MainProcess - 90744 - gpt-4o-M3: completed for Task ID: 76, LLM Time: 19.65s
2025-03-14 15:22:36,945 - Default - MainProcess - 91093 - CanonicalCode: starts for Task ID: 76
2025-03-14 15:22:59,182 - Default - MainProcess - 91093 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.438
----------------------

2025-03-14 15:22:59,787 - Default - MainProcess - 91093 - CanonicalCode: completed for Task ID: 76, LLM Time: 16.68s
2025-03-14 15:24:14,398 - Default - MainProcess - 91655 - o3-mini-M3: starts for Task ID: 75
2025-03-14 15:24:52,385 - Default - MainProcess - 91655 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.826
----------------------

2025-03-14 15:24:52,975 - Default - MainProcess - 91655 - o3-mini-M3: completed for Task ID: 75, LLM Time: 33.05s
2025-03-14 15:26:01,789 - Default - MainProcess - 92417 - CanonicalCode: starts for Task ID: 78
2025-03-14 15:26:39,609 - Default - MainProcess - 92417 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.506
----------------------

2025-03-14 15:26:40,200 - Default - MainProcess - 92417 - CanonicalCode: completed for Task ID: 78, LLM Time: 32.20s
2025-03-14 15:26:58,456 - Default - MainProcess - 92776 - CanonicalCode: starts for Task ID: 79
2025-03-14 15:27:31,380 - Default - MainProcess - 92776 - Count 1:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\xb0' in file \\mac\Home\Downloads\codedemo\sample.py on line 213, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 15:27:52,721 - Default - MainProcess - 92776 - Count 2:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\xb0' in file \\mac\Home\Downloads\codedemo\sample.py on line 217, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 15:27:52,722 - Default - MainProcess - 92776 - CanonicalCode Error detected for Task ID: 79
2025-03-14 15:27:52,722 - Default - MainProcess - 92776 - CanonicalCode: completed for Task ID: 79, LLM Time: 32.11s
2025-03-14 15:27:58,546 - Default - MainProcess - 93147 - CanonicalCode: starts for Task ID: 79
2025-03-14 15:28:35,674 - Default - MainProcess - 93147 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.978
----------------------

2025-03-14 15:28:36,260 - Default - MainProcess - 93147 - CanonicalCode: completed for Task ID: 79, LLM Time: 31.04s
2025-03-14 15:29:11,237 - Default - MainProcess - 93621 - gpt-4o-M3: starts for Task ID: 78
2025-03-14 15:29:36,159 - Default - MainProcess - 93621 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 6.383
----------------------

2025-03-14 15:29:36,769 - Default - MainProcess - 93621 - gpt-4o-M3: completed for Task ID: 78, LLM Time: 18.42s
2025-03-14 15:29:45,173 - Default - MainProcess - 93819 - gpt-4o-M3: starts for Task ID: 79
2025-03-14 15:30:12,936 - Default - MainProcess - 93819 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.937
----------------------

2025-03-14 15:30:13,599 - Default - MainProcess - 93819 - gpt-4o-M3: completed for Task ID: 79, LLM Time: 21.71s
2025-03-14 15:30:28,282 - Default - MainProcess - 94110 - gpt-4o-M3: starts for Task ID: 79
2025-03-14 15:30:50,405 - Default - MainProcess - 94110 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 315, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 218, in main
    ECAMdata = ECAMData()
               ^^^^^^^^
NameError: name 'ECAMData' is not defined. Did you mean: 'ECAMdata'?
!!!
----------------------

2025-03-14 15:31:22,921 - Default - MainProcess - 94110 - Count 2:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 318, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 222, in main
    set_single_turn_mode(6, True, 360)
    ^^^^^^^^^^^^^^^^^^^^
NameError: name 'set_single_turn_mode' is not defined
!!!
----------------------

2025-03-14 15:31:22,923 - Default - MainProcess - 94110 - gpt-4o-M3 Error detected for Task ID: 79
2025-03-14 15:31:22,923 - Default - MainProcess - 94110 - gpt-4o-M3: completed for Task ID: 79, LLM Time: 18.58s
2025-03-14 15:31:29,004 - Default - MainProcess - 94453 - gpt-4o-M3: starts for Task ID: 79
2025-03-14 15:31:52,244 - Default - MainProcess - 94453 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.172
----------------------

2025-03-14 15:31:52,861 - Default - MainProcess - 94453 - gpt-4o-M3: completed for Task ID: 79, LLM Time: 17.96s
2025-03-14 15:32:38,118 - Default - MainProcess - 94874 - gpt-4o-M3: starts for Task ID: 81
2025-03-14 15:33:00,246 - Default - MainProcess - 94874 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.138
----------------------

2025-03-14 15:33:00,746 - Default - MainProcess - 94874 - gpt-4o-M3: completed for Task ID: 81, LLM Time: 17.87s
2025-03-14 15:33:14,390 - Default - MainProcess - 95118 - gpt-4o-M3: starts for Task ID: 81
2025-03-14 15:33:31,004 - Default - MainProcess - 95118 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.001
----------------------

2025-03-14 15:33:31,604 - Default - MainProcess - 95118 - gpt-4o-M3: completed for Task ID: 81, LLM Time: 12.51s
2025-03-14 15:33:42,142 - Default - MainProcess - 95326 - gpt-4o-M3: starts for Task ID: 81
2025-03-14 15:34:03,290 - Default - MainProcess - 95326 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.192
----------------------

2025-03-14 15:34:03,851 - Default - MainProcess - 95326 - gpt-4o-M3: completed for Task ID: 81, LLM Time: 16.82s
2025-03-14 15:34:25,887 - Default - MainProcess - 95570 - gpt-4o-M3: starts for Task ID: 81
2025-03-14 15:34:48,153 - Default - MainProcess - 95570 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.164
----------------------

2025-03-14 15:34:48,701 - Default - MainProcess - 95570 - gpt-4o-M3: completed for Task ID: 81, LLM Time: 17.99s
2025-03-14 15:34:58,821 - Default - MainProcess - 95825 - gpt-4o-M3: starts for Task ID: 81
2025-03-14 15:35:18,636 - Default - MainProcess - 95825 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.307
----------------------

2025-03-14 15:35:19,173 - Default - MainProcess - 95825 - gpt-4o-M3: completed for Task ID: 81, LLM Time: 15.40s
2025-03-14 15:35:51,153 - Default - MainProcess - 96124 - CanonicalCode: starts for Task ID: 81
2025-03-14 15:36:11,034 - Default - MainProcess - 96124 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.931
----------------------

2025-03-14 15:36:11,537 - Default - MainProcess - 96124 - CanonicalCode: completed for Task ID: 81, LLM Time: 15.83s
2025-03-14 15:36:22,917 - Default - MainProcess - 96322 - CanonicalCode: starts for Task ID: 81
2025-03-14 15:36:42,338 - Default - MainProcess - 96322 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.834
----------------------

2025-03-14 15:36:42,867 - Default - MainProcess - 96322 - CanonicalCode: completed for Task ID: 81, LLM Time: 15.48s
2025-03-14 15:36:54,859 - Default - MainProcess - 96505 - CanonicalCode: starts for Task ID: 81
2025-03-14 15:37:22,895 - Default - MainProcess - 96505 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.842
----------------------

2025-03-14 15:37:23,518 - Default - MainProcess - 96505 - CanonicalCode: completed for Task ID: 81, LLM Time: 24.08s
2025-03-14 15:37:44,672 - Default - MainProcess - 96817 - CanonicalCode: starts for Task ID: 81
2025-03-14 15:38:03,391 - Default - MainProcess - 96817 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.946
----------------------

2025-03-14 15:38:03,918 - Default - MainProcess - 96817 - CanonicalCode: completed for Task ID: 81, LLM Time: 14.66s
2025-03-14 15:38:17,867 - Default - MainProcess - 96997 - CanonicalCode: starts for Task ID: 81
2025-03-14 15:38:43,030 - Default - MainProcess - 96997 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.308
----------------------

2025-03-14 15:38:43,590 - Default - MainProcess - 96997 - CanonicalCode: completed for Task ID: 81, LLM Time: 20.75s
2025-03-14 15:39:01,897 - Default - MainProcess - 97256 - CanonicalCode: starts for Task ID: 81
2025-03-14 15:39:39,985 - Default - MainProcess - 97256 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.208
----------------------

2025-03-14 15:39:40,540 - Default - MainProcess - 97256 - CanonicalCode: completed for Task ID: 81, LLM Time: 33.77s
2025-03-14 16:04:19,234 - Default - MainProcess - 5482 - CanonicalCode: starts for Task ID: 81
2025-03-14 16:05:02,416 - Default - MainProcess - 5482 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.001
----------------------

2025-03-14 16:05:02,982 - Default - MainProcess - 5482 - CanonicalCode: completed for Task ID: 81, LLM Time: 38.07s
2025-03-14 16:05:20,801 - Default - MainProcess - 5824 - CanonicalCode: starts for Task ID: 81
2025-03-14 16:06:03,299 - Default - MainProcess - 5824 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.890
----------------------

2025-03-14 16:06:03,850 - Default - MainProcess - 5824 - CanonicalCode: completed for Task ID: 81, LLM Time: 38.50s
2025-03-14 16:06:15,563 - Default - MainProcess - 6134 - CanonicalCode: starts for Task ID: 81
2025-03-14 16:06:48,648 - Default - MainProcess - 6134 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.114
----------------------

2025-03-14 16:06:49,172 - Default - MainProcess - 6134 - CanonicalCode: completed for Task ID: 81, LLM Time: 28.86s
2025-03-14 16:07:09,532 - Default - MainProcess - 6432 - CanonicalCode: starts for Task ID: 81
2025-03-14 16:07:44,727 - Default - MainProcess - 6432 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.955
----------------------

2025-03-14 16:07:45,278 - Default - MainProcess - 6432 - CanonicalCode: completed for Task ID: 81, LLM Time: 31.13s
2025-03-14 16:11:04,518 - Default - MainProcess - 7643 - o3-mini-M3: starts for Task ID: 93
2025-03-14 16:11:30,749 - Default - MainProcess - 7643 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 287, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 228, in main
    ret = Wmx3Lib_cm.motion.Home(axis)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 8625, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Motion, name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Motion' object has no attribute 'Home'
!!!
----------------------

2025-03-14 16:11:49,756 - Default - MainProcess - 7643 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 2.972
----------------------

2025-03-14 16:11:50,304 - Default - MainProcess - 7643 - o3-mini-M3: completed for Task ID: 93, LLM Time: 23.06s
2025-03-14 16:14:48,700 - Default - MainProcess - 8859 - o3-mini-M3: starts for Task ID: 107
2025-03-14 16:15:29,571 - Default - MainProcess - 8859 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 329, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 20, in main
    sleep(0.1)
    ^^^^^
UnboundLocalError: cannot access local variable 'sleep' where it is not associated with a value
!!!
----------------------

2025-03-14 16:15:59,076 - Default - MainProcess - 8859 - Count 2:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 327, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 228, in main
    ret = Wmx3Lib_Io.SetOutBit(0x0, 7, 1)  # byte 0, bit 7
          ^^^^^^^^^^
NameError: name 'Wmx3Lib_Io' is not defined. Did you mean: 'Wmx3Lib_cm'?
!!!
----------------------

2025-03-14 16:15:59,077 - Default - MainProcess - 8859 - o3-mini-M3 Error detected for Task ID: 107
2025-03-14 16:15:59,077 - Default - MainProcess - 8859 - o3-mini-M3: completed for Task ID: 107, LLM Time: 39.79s
2025-03-14 16:16:10,615 - Default - MainProcess - 9307 - o3-mini-M3: starts for Task ID: 107
2025-03-14 16:16:53,880 - Default - MainProcess - 9307 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 4.081
----------------------

2025-03-14 16:16:54,451 - Default - MainProcess - 9307 - o3-mini-M3: completed for Task ID: 107, LLM Time: 39.08s
2025-03-14 16:19:50,259 - Default - MainProcess - 10446 - o3-mini-M3: starts for Task ID: 115
2025-03-14 16:20:50,023 - Default - MainProcess - 10784 - CanonicalCode: starts for Task ID: 115
2025-03-14 16:21:32,975 - Default - MainProcess - 10784 - Count 1:
codedata:
Program begin.
StartPos error code for Axis 5: 65582
Program End.
Elapsed_time: 6.124
----------------------

2025-03-14 16:22:09,645 - Default - MainProcess - 10784 - Count 2:
codedata:
Program begin.
StartPos error code for Axis 5: 65582
Program End.
Elapsed_time: 5.700
----------------------

2025-03-14 16:22:09,646 - Default - MainProcess - 10784 - CanonicalCode Error detected for Task ID: 115
2025-03-14 16:22:09,646 - Default - MainProcess - 10784 - CanonicalCode: completed for Task ID: 115, LLM Time: 36.71s
2025-03-14 16:22:22,148 - Default - MainProcess - 11302 - CanonicalCode: starts for Task ID: 115
2025-03-14 16:23:04,629 - Default - MainProcess - 11302 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 6.384
----------------------

2025-03-14 16:23:05,264 - Default - MainProcess - 11302 - CanonicalCode: completed for Task ID: 115, LLM Time: 35.99s
2025-03-14 16:25:02,484 - Default - MainProcess - 12219 - gpt-4o-M3: starts for Task ID: 115
2025-03-14 16:25:29,636 - Default - MainProcess - 12219 - Count 1:
codedata:
Program begin.
StartPos error code is 65582: [0x0001002e] : CoreMotionApi Error: One or more acceleration arguments out of range.
Elapsed_time: 3.581
----------------------

2025-03-14 16:25:50,798 - Default - MainProcess - 12219 - Count 2:
codedata:
Program begin.
StartCircularIntplPos_CenterAndLength error code is 65582: [0x0001002e] : CoreMotionApi Error: One or more acceleration arguments out of range.
Program End.
Elapsed_time: 4.608
----------------------

2025-03-14 16:25:50,799 - Default - MainProcess - 12219 - gpt-4o-M3 Error detected for Task ID: 115
2025-03-14 16:25:50,799 - Default - MainProcess - 12219 - gpt-4o-M3: completed for Task ID: 115, LLM Time: 23.46s
2025-03-14 16:25:58,076 - Default - MainProcess - 12522 - gpt-4o-M3: starts for Task ID: 115
2025-03-14 16:26:35,311 - Default - MainProcess - 12522 - Count 1:
codedata:
Program begin.
StartPos error code is 65582: [0x0001002e] : CoreMotionApi Error: One or more acceleration arguments out of range.
Program End.
Elapsed_time: 6.052
----------------------

2025-03-14 16:26:59,556 - Default - MainProcess - 12522 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 6.289
----------------------

2025-03-14 16:27:00,176 - Default - MainProcess - 12522 - gpt-4o-M3: completed for Task ID: 115, LLM Time: 31.07s
2025-03-14 16:28:32,042 - Default - MainProcess - 13348 - o3-mini-M3: starts for Task ID: 118
2025-03-14 16:28:58,337 - Default - MainProcess - 13348 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 275, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 217, in main
    posCommand.profile.type = ProfileType.twoVelTrapezoidal
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'twoVelTrapezoidal'. Did you mean: 'TwoVelocityTrapezoidal'?
!!!
----------------------

2025-03-14 16:29:13,014 - Default - MainProcess - 13348 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 3.280
----------------------

2025-03-14 16:29:13,588 - Default - MainProcess - 13348 - o3-mini-M3: completed for Task ID: 118, LLM Time: 23.28s
2025-03-14 16:29:33,682 - Default - MainProcess - 13703 - o3-mini-M3: starts for Task ID: 119
2025-03-14 16:29:56,390 - Default - MainProcess - 13703 - Count 1:
codedata:
Program begin.
StartPos error code is 65586: [0x00010032] : CoreMotionApi Error: One or more acceleration jerk ratio arguments out of range.
Program End.
Elapsed_time: 3.406
----------------------

2025-03-14 16:30:09,110 - Default - MainProcess - 13703 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 3.203
----------------------

2025-03-14 16:30:09,663 - Default - MainProcess - 13703 - o3-mini-M3: completed for Task ID: 119, LLM Time: 19.19s
2025-03-14 16:30:52,408 - Default - MainProcess - 14145 - o3-mini-M3: starts for Task ID: 120
2025-03-14 16:31:10,120 - Default - MainProcess - 14145 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 272, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212, in main
    posCommand.profile.type = ProfileType.Cosine
                              ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Cosine'
!!!
----------------------

2025-03-14 16:31:27,726 - Default - MainProcess - 14145 - Count 2:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 272, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 213, in main
    posCommand.profile.type = ProfileType.Sine  # Use Sine profile in place of the non-existent Cosine profile.
                              ^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Sine'. Did you mean: 'Sin'?
!!!
----------------------

2025-03-14 16:31:27,727 - Default - MainProcess - 14145 - o3-mini-M3 Error detected for Task ID: 120
2025-03-14 16:31:27,728 - Default - MainProcess - 14145 - o3-mini-M3: completed for Task ID: 120, LLM Time: 14.52s
2025-03-14 16:31:40,410 - Default - MainProcess - 14451 - o3-mini-M3: starts for Task ID: 120
2025-03-14 16:32:01,594 - Default - MainProcess - 14451 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 270, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212, in main
    posCommand.profile.type = ProfileType.Cosine
                              ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Cosine'
!!!
----------------------

2025-03-14 16:32:29,073 - Default - MainProcess - 14451 - Count 2:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 270, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212, in main
    posCommand.profile.type = ProfileType.Sine  # Corrected: use Sine instead of Cosine.
                              ^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Sine'. Did you mean: 'Sin'?
!!!
----------------------

2025-03-14 16:32:29,074 - Default - MainProcess - 14451 - o3-mini-M3 Error detected for Task ID: 120
2025-03-14 16:32:29,074 - Default - MainProcess - 14451 - o3-mini-M3: completed for Task ID: 120, LLM Time: 18.43s
2025-03-14 16:32:59,049 - Default - MainProcess - 14897 - o3-mini-M3: starts for Task ID: 120
2025-03-14 16:33:18,084 - Default - MainProcess - 14897 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 271, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212, in main
    posCommand.profile.type = ProfileType.Cosine
                              ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Cosine'
!!!
----------------------

2025-03-14 16:33:35,647 - Default - MainProcess - 14897 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 272, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 213, in main
    posCommand.profile.type = ProfileType.Sine
                              ^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Sine'. Did you mean: 'Sin'?
!!!
----------------------

2025-03-14 16:33:52,786 - Default - MainProcess - 14897 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 3.634
----------------------

2025-03-14 16:33:53,358 - Default - MainProcess - 14897 - o3-mini-M3: completed for Task ID: 120, LLM Time: 16.34s
2025-03-14 16:34:31,321 - Default - MainProcess - 15396 - o3-mini-M3: starts for Task ID: 123
2025-03-14 16:35:03,021 - Default - MainProcess - 15396 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 308, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 20, in main
    sleep(0.1)
    ^^^^^
UnboundLocalError: cannot access local variable 'sleep' where it is not associated with a value
!!!
----------------------

2025-03-14 16:35:33,540 - Default - MainProcess - 15396 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 6.715
----------------------

2025-03-14 16:35:34,134 - Default - MainProcess - 15396 - o3-mini-M3: completed for Task ID: 123, LLM Time: 30.75s
2025-03-14 16:35:47,749 - Default - MainProcess - 15815 - o3-mini-M3: starts for Task ID: 125
2025-03-14 16:36:08,920 - Default - MainProcess - 15815 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.661
----------------------

2025-03-14 16:36:09,492 - Default - MainProcess - 15815 - o3-mini-M3: completed for Task ID: 125, LLM Time: 17.40s
2025-03-14 16:37:21,934 - Default - MainProcess - 16301 - o3-mini-M3: starts for Task ID: 129
2025-03-14 16:37:42,216 - Default - MainProcess - 16301 - Count 0:
codedata:
Program begin.
StartPos error code is 65583: [0x0001002f] : CoreMotionApi Error: One or more deceleration arguments out of range.
Program End.
Elapsed_time: 3.259
----------------------

2025-03-14 16:38:11,385 - Default - MainProcess - 16301 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 9.890
----------------------

2025-03-14 16:38:11,942 - Default - MainProcess - 16301 - o3-mini-M3: completed for Task ID: 129, LLM Time: 16.91s
2025-03-14 16:38:46,730 - Default - MainProcess - 16755 - o3-mini-M3: starts for Task ID: 132
2025-03-14 16:39:36,317 - Default - MainProcess - 16755 - Count 0:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x92' in file \\mac\Home\Downloads\codedemo\sample.py on line 222, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 16:40:07,534 - Default - MainProcess - 16755 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 6.596
----------------------

2025-03-14 16:40:08,139 - Default - MainProcess - 16755 - o3-mini-M3: completed for Task ID: 132, LLM Time: 48.67s
2025-03-14 16:40:29,245 - Default - MainProcess - 17290 - o3-mini-M3: starts for Task ID: 134
2025-03-14 16:40:47,840 - Default - MainProcess - 17290 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 270, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212, in main
    posCommand.profile.type = ProfileType.Sine
                              ^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Sine'. Did you mean: 'Sin'?
!!!
----------------------

2025-03-14 16:40:59,938 - Default - MainProcess - 17290 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.701
----------------------

2025-03-14 16:41:00,512 - Default - MainProcess - 17290 - o3-mini-M3: completed for Task ID: 134, LLM Time: 15.39s
2025-03-14 16:41:13,157 - Default - MainProcess - 17544 - o3-mini-M3: starts for Task ID: 135
2025-03-14 16:42:17,015 - Default - MainProcess - 17544 - Count 0:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x92' in file \\mac\Home\Downloads\codedemo\sample.py on line 210, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 16:42:45,365 - Default - MainProcess - 17544 - Count 1:

2025-03-14 16:42:45,779 - Default - MainProcess - 17544 - o3-mini-M3: completed for Task ID: 135, LLM Time: 62.94s
2025-03-14 16:43:02,696 - Default - MainProcess - 18121 - o3-mini-M3: starts for Task ID: 135
2025-03-14 16:44:03,139 - Default - MainProcess - 18121 - Count 0:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x92' in file \\mac\Home\Downloads\codedemo\sample.py on line 211, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 16:44:26,168 - Default - MainProcess - 18121 - Count 1:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x92' in file \\mac\Home\Downloads\codedemo\sample.py on line 212, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 16:44:54,585 - Default - MainProcess - 18121 - Count 2:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 345, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 254, in main
    multiPosCommand = Motion_LinearIntplPosCommand()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'Motion_LinearIntplPosCommand' is not defined
!!!
----------------------

2025-03-14 16:44:54,587 - Default - MainProcess - 18121 - o3-mini-M3 Error detected for Task ID: 135
2025-03-14 16:44:54,587 - Default - MainProcess - 18121 - o3-mini-M3: completed for Task ID: 135, LLM Time: 59.53s
2025-03-14 16:45:00,942 - Default - MainProcess - 18781 - o3-mini-M3: starts for Task ID: 137
2025-03-14 16:46:05,105 - Default - MainProcess - 18781 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 8.531
----------------------

2025-03-14 16:46:05,698 - Default - MainProcess - 18781 - o3-mini-M3: completed for Task ID: 137, LLM Time: 55.53s
2025-03-14 16:46:36,047 - Default - MainProcess - 19295 - o3-mini-M3: starts for Task ID: 141
2025-03-14 16:47:19,304 - Default - MainProcess - 19295 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 5.093
----------------------

2025-03-14 16:47:19,871 - Default - MainProcess - 19295 - o3-mini-M3: completed for Task ID: 141, LLM Time: 38.05s
2025-03-14 16:50:00,417 - Default - MainProcess - 20432 - gpt-4o-M3: starts for Task ID: 141
2025-03-14 16:50:31,743 - Default - MainProcess - 20432 - Count 0:
codedata:
Program begin.
SetEvent_ID error code is 90120
Elapsed_time: 3.512
----------------------

2025-03-14 16:50:57,687 - Default - MainProcess - 20432 - Count 1:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 337, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 256, in main
    posEventID_Axis10_Axis2, available = Wmx3Lib_EventCtl.GetAvailableEventID()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 21371, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, EventControl, name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'EventControl' object has no attribute 'GetAvailableEventID'
!!!
----------------------

2025-03-14 16:51:21,214 - Default - MainProcess - 20432 - Count 2:
codedata:
Program begin.
Program End.
Elapsed_time: 6.155
----------------------

2025-03-14 16:51:21,777 - Default - MainProcess - 20432 - gpt-4o-M3: completed for Task ID: 141, LLM Time: 27.70s
2025-03-14 16:51:55,691 - Default - MainProcess - 21060 - gpt-4o-M3: starts for Task ID: 143
2025-03-14 16:52:24,727 - Default - MainProcess - 21060 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 6.479
----------------------

2025-03-14 16:52:25,333 - Default - MainProcess - 21060 - gpt-4o-M3: completed for Task ID: 143, LLM Time: 22.45s
2025-03-14 16:53:40,707 - Default - MainProcess - 21618 - gpt-4o-M3: starts for Task ID: 143
2025-03-14 16:54:10,590 - Default - MainProcess - 21618 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 5.418
----------------------

2025-03-14 16:54:11,139 - Default - MainProcess - 21618 - gpt-4o-M3: completed for Task ID: 143, LLM Time: 24.36s
2025-03-14 16:54:45,689 - Default - MainProcess - 22026 - CanonicalCode: starts for Task ID: 143
2025-03-14 16:55:23,062 - Default - MainProcess - 22026 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 5.517
----------------------

2025-03-14 16:55:23,632 - Default - MainProcess - 22026 - CanonicalCode: completed for Task ID: 143, LLM Time: 31.75s
2025-03-14 16:55:47,596 - Default - MainProcess - 22440 - o3-mini-M3: starts for Task ID: 143
2025-03-14 16:56:54,540 - Default - MainProcess - 22811 - o3-mini-M3: starts for Task ID: 143
2025-03-14 16:57:40,518 - Default - MainProcess - 22811 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 8.503
----------------------

2025-03-14 16:57:41,131 - Default - MainProcess - 22811 - o3-mini-M3: completed for Task ID: 143, LLM Time: 37.36s
2025-03-14 16:59:15,715 - Default - MainProcess - 23567 - o3-mini-M3: starts for Task ID: 146
2025-03-14 16:59:37,392 - Default - MainProcess - 23567 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 288, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 213, in main
    posCommand.profile.type = ProfileType.Sine
                              ^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'Sine'. Did you mean: 'Sin'?
!!!
----------------------

2025-03-14 16:59:53,606 - Default - MainProcess - 23567 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.673
----------------------

2025-03-14 16:59:54,196 - Default - MainProcess - 23567 - o3-mini-M3: completed for Task ID: 146, LLM Time: 18.65s
2025-03-14 17:00:32,342 - Default - MainProcess - 23984 - o3-mini-M3: starts for Task ID: 156
2025-03-14 17:01:27,307 - Default - MainProcess - 23984 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 355, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 20, in main
    sleep(0.1)
    ^^^^^
UnboundLocalError: cannot access local variable 'sleep' where it is not associated with a value
!!!
----------------------

2025-03-14 17:01:52,229 - Default - MainProcess - 23984 - Count 1:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x96' in file \\mac\Home\Downloads\codedemo\sample.py on line 213, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 17:02:15,609 - Default - MainProcess - 23984 - Count 2:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x96' in file \\mac\Home\Downloads\codedemo\sample.py on line 214, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 17:02:15,610 - Default - MainProcess - 23984 - o3-mini-M3 Error detected for Task ID: 156
2025-03-14 17:02:15,610 - Default - MainProcess - 23984 - o3-mini-M3: completed for Task ID: 156, LLM Time: 53.92s
2025-03-14 17:02:26,763 - Default - MainProcess - 24604 - o3-mini-M3: starts for Task ID: 156
2025-03-14 17:03:30,079 - Default - MainProcess - 24604 - Count 0:
codedata:
Program begin.
SetEvent_ID error code: 90120
Program End.
Elapsed_time: 6.733
----------------------

2025-03-14 17:04:02,507 - Default - MainProcess - 24604 - Count 1:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x92' in file \\mac\Home\Downloads\codedemo\sample.py on line 215, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 17:04:24,273 - Default - MainProcess - 24604 - Count 2:
codeerr:
SyntaxError: Non-UTF-8 code starting with '\x92' in file \\mac\Home\Downloads\codedemo\sample.py on line 216, but no encoding declared; see https://peps.python.org/pep-0263/ for details
!!!
----------------------

2025-03-14 17:04:24,275 - Default - MainProcess - 24604 - o3-mini-M3 Error detected for Task ID: 156
2025-03-14 17:04:24,275 - Default - MainProcess - 24604 - o3-mini-M3: completed for Task ID: 156, LLM Time: 56.47s
2025-03-14 17:04:30,777 - Default - MainProcess - 25256 - o3-mini-M3: starts for Task ID: 158
2025-03-14 17:04:53,657 - Default - MainProcess - 25256 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 266, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212, in main
    posCommand.profile.type = ProfileType.TwoVelJerkRatio
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ProfileType' has no attribute 'TwoVelJerkRatio'. Did you mean: 'TwoVelocityJerkRatio'?
!!!
----------------------

2025-03-14 17:05:24,878 - Default - MainProcess - 25256 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 3.106
----------------------

2025-03-14 17:05:25,401 - Default - MainProcess - 25256 - o3-mini-M3: completed for Task ID: 158, LLM Time: 19.93s
2025-03-14 17:07:07,251 - Default - MainProcess - 26094 - o3-mini-M3: starts for Task ID: 169
2025-03-14 17:07:53,687 - Default - MainProcess - 26094 - Count 0:

2025-03-14 17:07:54,218 - Default - MainProcess - 26094 - o3-mini-M3: completed for Task ID: 169, LLM Time: 46.29s
2025-03-14 17:08:07,071 - Default - MainProcess - 26425 - o3-mini-M3: starts for Task ID: 169
2025-03-14 17:09:22,327 - Default - MainProcess - 26425 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.586
----------------------

2025-03-14 17:09:22,903 - Default - MainProcess - 26425 - o3-mini-M3: completed for Task ID: 169, LLM Time: 59.56s
2025-03-14 17:11:41,801 - Default - MainProcess - 27587 - gpt-4o-M3: starts for Task ID: 173
2025-03-14 17:12:08,607 - Default - MainProcess - 27587 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.471
----------------------

2025-03-14 17:12:09,164 - Default - MainProcess - 27587 - gpt-4o-M3: completed for Task ID: 173, LLM Time: 22.23s
2025-03-14 17:12:44,241 - Default - MainProcess - 27941 - CanonicalCode: starts for Task ID: 173
2025-03-14 17:13:02,532 - Default - MainProcess - 27941 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.493
----------------------

2025-03-14 17:13:03,122 - Default - MainProcess - 27941 - CanonicalCode: completed for Task ID: 173, LLM Time: 13.69s
2025-03-14 17:14:48,195 - Default - MainProcess - 28617 - CanonicalCode: starts for Task ID: 173
2025-03-14 17:15:13,644 - Default - MainProcess - 28617 - Count 0:
codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 297, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 228, in main
    ret, CmStatus_12 = Wmx3Lib_cm.GetStatus(12)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CoreMotion.GetStatus() takes 1 positional argument but 2 were given
!!!
----------------------

2025-03-14 17:15:29,415 - Default - MainProcess - 28845 - CanonicalCode: starts for Task ID: 173
2025-03-14 17:16:00,252 - Default - MainProcess - 28845 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 5.120
----------------------

2025-03-14 17:16:00,872 - Default - MainProcess - 28845 - CanonicalCode: completed for Task ID: 173, LLM Time: 25.61s
2025-03-14 17:16:59,030 - Default - MainProcess - 29338 - o3-mini-M3: starts for Task ID: 176
2025-03-14 17:17:23,662 - Default - MainProcess - 29338 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.554
----------------------

2025-03-14 17:17:24,220 - Default - MainProcess - 29338 - o3-mini-M3: completed for Task ID: 176, LLM Time: 19.96s
2025-03-14 17:18:45,072 - Default - MainProcess - 29948 - o3-mini-M3: starts for Task ID: 177
2025-03-14 17:19:32,350 - Default - MainProcess - 29948 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 3.743
----------------------

2025-03-14 17:19:32,939 - Default - MainProcess - 29948 - o3-mini-M3: completed for Task ID: 177, LLM Time: 43.42s
2025-03-14 17:21:55,708 - Default - MainProcess - 30925 - o3-mini-M3: starts for Task ID: 177
2025-03-14 17:22:50,830 - Default - MainProcess - 30925 - Count 0:
codedata:
Program begin.
Program End.
Elapsed_time: 4.543
----------------------

2025-03-14 17:22:51,461 - Default - MainProcess - 30925 - o3-mini-M3: completed for Task ID: 177, LLM Time: 50.46s
2025-03-14 17:23:41,499 - Default - MainProcess - 31522 - o3-mini-M3: starts for Task ID: 183
2025-03-14 17:24:04,487 - Default - MainProcess - 31522 - Count 0:
codedata:
Program begin.
StartPos error code is 65581: [0x0001002d] : CoreMotionApi Error: One or more velocity arguments out of range.
Program End.
Elapsed_time: 3.208
----------------------

2025-03-14 17:24:22,031 - Default - MainProcess - 31522 - Count 1:
codedata:
Program begin.
Program End.
Elapsed_time: 5.047
----------------------

2025-03-14 17:24:22,589 - Default - MainProcess - 31522 - o3-mini-M3: completed for Task ID: 183, LLM Time: 19.66s
2025-03-14 17:51:57,390 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 1
2025-03-14 17:54:49,065 - Default - MainProcess - 40593 - codedata:
Program begin.
Program End.
Elapsed_time: 3.705
----------------------

2025-03-14 17:54:49,616 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 1, LLM Time: 167.86s
2025-03-14 17:54:49,718 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 2
2025-03-14 17:55:52,438 - Default - MainProcess - 40593 - codedata:
Program begin.
Program End.
Elapsed_time: 3.387
----------------------

2025-03-14 17:55:52,850 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 2, LLM Time: 59.23s
2025-03-14 17:55:52,951 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 3
2025-03-14 17:56:52,165 - Default - MainProcess - 40593 - codedata:
Program begin.
Program End.
Elapsed_time: 3.524
----------------------

2025-03-14 17:56:52,572 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 3, LLM Time: 55.58s
2025-03-14 17:56:52,674 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 4
2025-03-14 17:57:38,928 - Default - MainProcess - 40593 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 288, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 210, in main
    if XYZ == 0:
       ^^^
NameError: name 'XYZ' is not defined
!!!
----------------------

2025-03-14 17:57:39,033 - Default - MainProcess - 40593 - DeepSeek-R1-M1 Error detected for Task ID: 4
2025-03-14 17:57:39,033 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 4, LLM Time: 43.14s
2025-03-14 17:57:39,137 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 5
2025-03-14 17:59:32,435 - Default - MainProcess - 40593 - codedata:
Program begin.
Program End.
Elapsed_time: 5.167
----------------------

2025-03-14 17:59:32,876 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 5, LLM Time: 108.02s
2025-03-14 17:59:32,979 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 6
2025-03-14 18:00:17,075 - Default - MainProcess - 40593 - codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 212
    posCommand = Motion_PosCommand()
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 18:00:17,178 - Default - MainProcess - 40593 - DeepSeek-R1-M1 Error detected for Task ID: 6
2025-03-14 18:00:17,178 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 6, LLM Time: 43.26s
2025-03-14 18:00:17,281 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 7
2025-03-14 18:02:59,818 - Default - MainProcess - 40593 - codedata:
Program begin.
Program End.
Elapsed_time: 3.736
----------------------

2025-03-14 18:03:00,274 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 7, LLM Time: 158.69s
2025-03-14 18:03:00,383 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 8
2025-03-14 18:07:37,752 - Default - MainProcess - 40593 - codedata:
Program begin.
Program End.
Elapsed_time: 5.118
----------------------

2025-03-14 18:07:38,245 - Default - MainProcess - 40593 - DeepSeek-R1-M1: completed for Task ID: 8, LLM Time: 272.14s
2025-03-14 18:07:38,347 - Default - MainProcess - 40593 - DeepSeek-R1-M1: starts for Task ID: 9
2025-03-14 18:55:01,987 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 8
2025-03-14 18:56:41,723 - Default - MainProcess - 60053 - codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211
    posCommand = Motion_PosCommand()
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 18:56:42,253 - Default - MainProcess - 60053 - DeepSeek-R1-M1 Error detected for Task ID: 8
2025-03-14 18:56:42,254 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 8, LLM Time: 98.69s
2025-03-14 18:56:42,355 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 9
2025-03-14 18:57:31,045 - Default - MainProcess - 60053 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 275, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211, in main
    if x == False:
       ^
NameError: name 'x' is not defined
!!!
----------------------

2025-03-14 18:57:31,150 - Default - MainProcess - 60053 - DeepSeek-R1-M1 Error detected for Task ID: 9
2025-03-14 18:57:31,150 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 9, LLM Time: 45.71s
2025-03-14 18:57:31,253 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 10
2025-03-14 18:58:22,795 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 3.623
----------------------

2025-03-14 18:58:23,226 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 10, LLM Time: 47.81s
2025-03-14 18:58:23,328 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 11
2025-03-14 19:00:18,290 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 4.426
----------------------

2025-03-14 19:00:18,714 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 11, LLM Time: 110.43s
2025-03-14 19:00:18,815 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 12
2025-03-14 19:01:25,443 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 4.243
----------------------

2025-03-14 19:01:25,865 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 12, LLM Time: 62.28s
2025-03-14 19:01:25,966 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 13
2025-03-14 19:03:02,948 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 11.384
----------------------

2025-03-14 19:03:03,389 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 13, LLM Time: 85.49s
2025-03-14 19:03:03,491 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 14
2025-03-14 19:06:28,332 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 3.351
----------------------

2025-03-14 19:06:28,750 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 14, LLM Time: 201.38s
2025-03-14 19:06:28,852 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 15
2025-03-14 19:07:55,101 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 4.671
----------------------

2025-03-14 19:07:55,550 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 15, LLM Time: 81.47s
2025-03-14 19:07:55,652 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 16
2025-03-14 19:09:29,165 - Default - MainProcess - 60053 - codeerr:
!!!
----------------------

2025-03-14 19:09:29,573 - Default - MainProcess - 60053 - DeepSeek-R1-M1 Error detected for Task ID: 16
2025-03-14 19:09:29,573 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 16, LLM Time: 88.73s
2025-03-14 19:09:29,676 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 17
2025-03-14 19:15:40,910 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 4.091
----------------------

2025-03-14 19:15:41,479 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 17, LLM Time: 367.03s
2025-03-14 19:15:41,581 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 18
2025-03-14 19:16:29,613 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 3.109
----------------------

2025-03-14 19:16:29,930 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 18, LLM Time: 44.80s
2025-03-14 19:16:30,032 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 19
2025-03-14 19:19:28,731 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 3.847
----------------------

2025-03-14 19:19:29,054 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 19, LLM Time: 174.74s
2025-03-14 19:19:29,161 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 20
2025-03-14 19:32:01,286 - Default - MainProcess - 60053 - codedata:
Program begin.
Program End.
Elapsed_time: 3.002
----------------------

2025-03-14 19:32:01,629 - Default - MainProcess - 60053 - DeepSeek-R1-M1: completed for Task ID: 20, LLM Time: 749.01s
2025-03-14 19:32:01,731 - Default - MainProcess - 60053 - DeepSeek-R1-M1: starts for Task ID: 21
2025-03-14 20:21:37,683 - Default - MainProcess - 86687 - DeepSeek-R1-M1: starts for Task ID: 21
2025-03-14 20:23:37,370 - Default - MainProcess - 86687 - codedata:
Program begin.
Program End.
Elapsed_time: 4.233
----------------------

2025-03-14 20:23:37,969 - Default - MainProcess - 86687 - DeepSeek-R1-M1: completed for Task ID: 21, LLM Time: 115.34s
2025-03-14 20:23:38,071 - Default - MainProcess - 86687 - DeepSeek-R1-M1: starts for Task ID: 22
2025-03-14 20:27:38,188 - Default - MainProcess - 86687 - codedata:
Program begin.
StartLinearIntplPos error code is 65585: [0x00010031] : CoreMotionApi Error: One or more deceleration jerk arguments out of range.
Elapsed_time: 3.525
----------------------

2025-03-14 20:27:38,631 - Default - MainProcess - 86687 - DeepSeek-R1-M1 Error detected for Task ID: 22
2025-03-14 20:27:38,632 - Default - MainProcess - 86687 - DeepSeek-R1-M1: completed for Task ID: 22, LLM Time: 236.48s
2025-03-14 20:27:38,734 - Default - MainProcess - 86687 - DeepSeek-R1-M1: starts for Task ID: 23
2025-03-14 20:28:34,467 - Default - MainProcess - 86687 - codedata:
Program begin.
Program End.
Elapsed_time: 3.644
----------------------

2025-03-14 20:28:34,899 - Default - MainProcess - 86687 - DeepSeek-R1-M1: completed for Task ID: 23, LLM Time: 51.98s
2025-03-14 20:28:35,001 - Default - MainProcess - 86687 - DeepSeek-R1-M1: starts for Task ID: 24
2025-03-14 20:32:07,331 - Default - MainProcess - 86687 - codedata:
Program begin.
Program End.
Elapsed_time: 4.733
----------------------

2025-03-14 20:32:07,822 - Default - MainProcess - 86687 - DeepSeek-R1-M1: completed for Task ID: 24, LLM Time: 207.49s
2025-03-14 20:32:07,924 - Default - MainProcess - 86687 - DeepSeek-R1-M1: starts for Task ID: 25
2025-03-14 21:17:01,260 - Default - MainProcess - 4302 - DeepSeek-R1-M1: starts for Task ID: 25
2025-03-14 21:18:38,762 - Default - MainProcess - 4302 - codedata:
Program begin.
Program End.
Elapsed_time: 4.245
----------------------

2025-03-14 21:18:39,328 - Default - MainProcess - 4302 - DeepSeek-R1-M1: completed for Task ID: 25, LLM Time: 93.14s
2025-03-14 21:18:39,430 - Default - MainProcess - 4302 - DeepSeek-R1-M1: starts for Task ID: 26
2025-03-14 21:20:03,611 - Default - MainProcess - 4302 - codedata:
Program begin.
Program End.
Elapsed_time: 4.312
----------------------

2025-03-14 21:20:04,036 - Default - MainProcess - 4302 - DeepSeek-R1-M1: completed for Task ID: 26, LLM Time: 79.76s
2025-03-14 21:20:04,138 - Default - MainProcess - 4302 - DeepSeek-R1-M1: starts for Task ID: 27
2025-03-14 21:24:52,650 - Default - MainProcess - 4302 - codedata:
Program begin.
PathIntplLookahead Running timeout!
Program End.
Elapsed_time: 57.852
----------------------

2025-03-14 21:24:53,220 - Default - MainProcess - 4302 - DeepSeek-R1-M1: completed for Task ID: 27, LLM Time: 230.55s
2025-03-14 21:24:53,322 - Default - MainProcess - 4302 - DeepSeek-R1-M1: starts for Task ID: 28
2025-03-14 21:27:12,522 - Default - MainProcess - 4302 - codedata:
Program begin.
Program End.
Elapsed_time: 5.189
----------------------

2025-03-14 21:27:12,965 - Default - MainProcess - 4302 - DeepSeek-R1-M1: completed for Task ID: 28, LLM Time: 133.90s
2025-03-14 21:27:13,067 - Default - MainProcess - 4302 - DeepSeek-R1-M1: starts for Task ID: 29
2025-03-14 21:32:35,231 - Default - MainProcess - 4302 - codedata:
Program begin.
Program End.
Elapsed_time: 4.331
----------------------

2025-03-14 21:32:35,716 - Default - MainProcess - 4302 - DeepSeek-R1-M1: completed for Task ID: 29, LLM Time: 317.72s
2025-03-14 21:32:35,826 - Default - MainProcess - 4302 - DeepSeek-R1-M1: starts for Task ID: 30
2025-03-14 21:59:16,153 - Default - MainProcess - 17506 - DeepSeek-R1-M1: starts for Task ID: 30
2025-03-14 22:01:29,186 - Default - MainProcess - 17506 - codedata:
Program begin.
Program End.
Elapsed_time: 4.206
----------------------

2025-03-14 22:01:29,735 - Default - MainProcess - 17506 - DeepSeek-R1-M1: completed for Task ID: 30, LLM Time: 128.72s
2025-03-14 22:01:29,839 - Default - MainProcess - 17506 - DeepSeek-R1-M1: starts for Task ID: 31
2025-03-14 22:02:31,812 - Default - MainProcess - 17506 - codedata:
Program begin.
Program End.
Elapsed_time: 4.339
----------------------

2025-03-14 22:02:32,255 - Default - MainProcess - 17506 - DeepSeek-R1-M1: completed for Task ID: 31, LLM Time: 57.53s
2025-03-14 22:02:32,356 - Default - MainProcess - 17506 - DeepSeek-R1-M1: starts for Task ID: 32
2025-03-14 22:17:25,672 - Default - MainProcess - 23216 - DeepSeek-R1-Distill-Llama-70B-M1: starts for Task ID: 1
2025-03-14 22:18:48,815 - Default - MainProcess - 23702 - DeepSeek-R1-Distill-Llama-70B-M1: starts for Task ID: 1
2025-03-14 22:19:24,299 - Default - MainProcess - 23914 - DeepSeek-R1-Distill-Llama-70B-M1: starts for Task ID: 1
2025-03-14 22:21:04,897 - Default - MainProcess - 24463 - DeepSeek-R1-Distill-Llama-70B-M1: starts for Task ID: 1
2025-03-14 22:25:49,306 - Default - MainProcess - 25965 - DeepSeek-R1-Distill-Llama-70B-M1: starts for Task ID: 1
2025-03-14 22:26:11,495 - Default - MainProcess - 26104 - DeepSeek-R1-Distill-Llama-70B-M1: starts for Task ID: 1
2025-03-14 22:28:49,072 - Default - MainProcess - 26949 - DeepSeek-R1-M1: starts for Task ID: 32
2025-03-14 22:30:49,802 - Default - MainProcess - 26949 - codedata:
Program begin.
Program End.
Elapsed_time: 5.382
----------------------

2025-03-14 22:30:50,392 - Default - MainProcess - 26949 - DeepSeek-R1-M1: completed for Task ID: 32, LLM Time: 115.24s
2025-03-14 22:30:50,494 - Default - MainProcess - 26949 - DeepSeek-R1-M1: starts for Task ID: 33
2025-03-14 22:32:32,827 - Default - MainProcess - 26949 - codedata:
Program begin.
Program End.
Elapsed_time: 5.402
----------------------

2025-03-14 22:32:33,282 - Default - MainProcess - 26949 - DeepSeek-R1-M1: completed for Task ID: 33, LLM Time: 96.82s
2025-03-14 22:32:33,384 - Default - MainProcess - 26949 - DeepSeek-R1-M1: starts for Task ID: 34
2025-03-14 22:35:04,572 - Default - MainProcess - 26949 - codedata:
Program begin.
Program End.
Elapsed_time: 4.199
----------------------

2025-03-14 22:35:05,001 - Default - MainProcess - 26949 - DeepSeek-R1-M1: completed for Task ID: 34, LLM Time: 146.88s
2025-03-14 22:35:05,102 - Default - MainProcess - 26949 - DeepSeek-R1-M1: starts for Task ID: 35
2025-03-14 22:41:06,638 - Default - MainProcess - 26949 - codedata:
Program begin.
Program End.
Elapsed_time: 4.218
----------------------

2025-03-14 22:41:07,075 - Default - MainProcess - 26949 - DeepSeek-R1-M1: completed for Task ID: 35, LLM Time: 357.21s
2025-03-14 22:41:07,176 - Default - MainProcess - 26949 - DeepSeek-R1-M1: starts for Task ID: 36
2025-03-14 22:43:44,218 - Default - MainProcess - 26949 - codedata:
Program begin.
Program End.
Elapsed_time: 4.835
----------------------

2025-03-14 22:43:44,650 - Default - MainProcess - 26949 - DeepSeek-R1-M1: completed for Task ID: 36, LLM Time: 152.10s
2025-03-14 22:43:44,753 - Default - MainProcess - 26949 - DeepSeek-R1-M1: starts for Task ID: 37
2025-03-14 23:09:02,339 - Default - MainProcess - 39317 - DeepSeek-R1-M1: starts for Task ID: 37
2025-03-14 23:11:59,633 - Default - MainProcess - 39317 - codedata:
Program begin.
Program End.
Elapsed_time: 4.268
----------------------

2025-03-14 23:12:00,280 - Default - MainProcess - 39317 - DeepSeek-R1-M1: completed for Task ID: 37, LLM Time: 172.92s
2025-03-14 23:12:00,382 - Default - MainProcess - 39317 - DeepSeek-R1-M1: starts for Task ID: 38
2025-03-14 23:16:07,213 - Default - MainProcess - 39317 - codedata:
Program begin.
Program End.
Elapsed_time: 3.826
----------------------

2025-03-14 23:16:07,662 - Default - MainProcess - 39317 - DeepSeek-R1-M1: completed for Task ID: 38, LLM Time: 242.89s
2025-03-14 23:16:07,764 - Default - MainProcess - 39317 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:29:54,983 - Default - MainProcess - 45926 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:32:42,265 - Default - MainProcess - 47925 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:33:24,608 - Default - MainProcess - 48198 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:37:42,694 - Default - MainProcess - 49781 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:38:02,046 - Default - MainProcess - 49918 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:38:20,007 - Default - MainProcess - 50904 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:39:05,163 - Default - MainProcess - 51175 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:39:21,879 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 39
2025-03-14 23:39:46,727 - Default - MainProcess - 51293 - codedata:
Program begin.
Program End.
Elapsed_time: 3.462
----------------------

2025-03-14 23:39:47,266 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 39, LLM Time: 21.27s
2025-03-14 23:39:47,368 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 40
2025-03-14 23:40:07,343 - Default - MainProcess - 51293 - codedata:
Program begin.
Program End.
Elapsed_time: 2.637
----------------------

2025-03-14 23:40:07,624 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 40, LLM Time: 17.23s
2025-03-14 23:40:07,726 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 41
2025-03-14 23:40:30,118 - Default - MainProcess - 51293 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 287, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 235, in main
    move_to_position_1(1, 66.6, 600)
  File "\\mac\Home\Downloads\codedemo\sample.py", line 218, in move_to_position_1
    ret = Wmx3Lib_cm.motion.StartPos(axis_num, target_position, velocity)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 8641, in StartPos
    return _WMX3ApiPython.Motion_StartPos(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Wrong number or type of arguments for overloaded function 'Motion_StartPos'.
  Possible C/C++ prototypes are:
    wmx3ApiPython::Motion::StartPos(wmx3ApiPython::Motion_PosCommand *)
    wmx3ApiPython::Motion::StartPos(unsigned int,PyObject *)

!!!
----------------------

2025-03-14 23:40:30,222 - Default - MainProcess - 51293 - DeepSeek-R1-M1 Error detected for Task ID: 41
2025-03-14 23:40:30,222 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 41, LLM Time: 19.39s
2025-03-14 23:40:30,325 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 42
2025-03-14 23:40:52,821 - Default - MainProcess - 51293 - codedata:
Program begin.
StartLinearIntplPos error code is 1549: [0x0000060d] : WMX3Api Error: Same axis specified more than once.
Elapsed_time: 3.420
----------------------

2025-03-14 23:40:53,236 - Default - MainProcess - 51293 - DeepSeek-R1-M1 Error detected for Task ID: 42
2025-03-14 23:40:53,236 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 42, LLM Time: 18.97s
2025-03-14 23:40:53,338 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 43
2025-03-14 23:41:18,577 - Default - MainProcess - 51293 - codedata:
Program begin.
StartLinearIntplPos error code is 1549: [0x0000060d] : WMX3Api Error: Same axis specified more than once.
Elapsed_time: 3.476
----------------------

2025-03-14 23:41:18,983 - Default - MainProcess - 51293 - DeepSeek-R1-M1 Error detected for Task ID: 43
2025-03-14 23:41:18,983 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 43, LLM Time: 21.66s
2025-03-14 23:41:19,085 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 44
2025-03-14 23:41:51,193 - Default - MainProcess - 51293 - codedata:
Program begin.
Program End.
Elapsed_time: 2.756
----------------------

2025-03-14 23:41:51,475 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 44, LLM Time: 29.25s
2025-03-14 23:41:51,576 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 45
2025-03-14 23:42:05,435 - Default - MainProcess - 51293 - codedata:
Program begin.
Program End.
Elapsed_time: 2.685
----------------------

2025-03-14 23:42:05,719 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 45, LLM Time: 11.07s
2025-03-14 23:42:05,820 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 46
2025-03-14 23:42:19,359 - Default - MainProcess - 51293 - codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 211
    for position in [50, -50, 100, -100]:
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 23:42:19,460 - Default - MainProcess - 51293 - DeepSeek-R1-M1 Error detected for Task ID: 46
2025-03-14 23:42:19,460 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 46, LLM Time: 12.75s
2025-03-14 23:42:19,563 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 47
2025-03-14 23:42:39,607 - Default - MainProcess - 51293 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 285, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 44, in main
    for axis in Axes:
                ^^^^
UnboundLocalError: cannot access local variable 'Axes' where it is not associated with a value
!!!
----------------------

2025-03-14 23:42:39,709 - Default - MainProcess - 51293 - DeepSeek-R1-M1 Error detected for Task ID: 47
2025-03-14 23:42:39,709 - Default - MainProcess - 51293 - DeepSeek-R1-M1: completed for Task ID: 47, LLM Time: 18.09s
2025-03-14 23:42:39,812 - Default - MainProcess - 51293 - DeepSeek-R1-M1: starts for Task ID: 48
2025-03-14 23:43:32,906 - Default - MainProcess - 52636 - DeepSeek-R1-M1: starts for Task ID: 47
2025-03-14 23:44:04,160 - Default - MainProcess - 52636 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 291, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 215, in main
    Wmx3Lib_cm = Wmx3LibCM()  # Assuming this is how you initialize the motion library
                 ^^^^^^^^^
NameError: name 'Wmx3LibCM' is not defined. Did you mean: 'Wmx3Lib'?
!!!
----------------------

2025-03-14 23:44:04,266 - Default - MainProcess - 52636 - DeepSeek-R1-M1 Error detected for Task ID: 47
2025-03-14 23:44:04,266 - Default - MainProcess - 52636 - DeepSeek-R1-M1: completed for Task ID: 47, LLM Time: 27.89s
2025-03-14 23:44:04,369 - Default - MainProcess - 52636 - DeepSeek-R1-M1: starts for Task ID: 48
2025-03-14 23:47:43,609 - Default - MainProcess - 54045 - DeepSeek-R1-M1: starts for Task ID: 47
2025-03-14 23:53:13,284 - Default - MainProcess - 54045 - codedata:
Program begin.
Program End.
Elapsed_time: 4.732
----------------------

2025-03-14 23:53:13,852 - Default - MainProcess - 54045 - DeepSeek-R1-M1: completed for Task ID: 47, LLM Time: 324.83s
2025-03-14 23:53:44,199 - Default - MainProcess - 55947 - DeepSeek-R1-M1: starts for Task ID: 48
2025-03-14 23:57:01,316 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 49
2025-03-14 23:57:37,055 - Default - MainProcess - 56952 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 303, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 213, in main
    pos_command.axis = [9, 12]  # Only set the axes you need to move
    ^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 7216, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, Motion_PosCommand, name, value)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mac\Home\Downloads\codedemo\WMX3ApiPython.py", line 60, in _swig_setattr_nondynamic
    return method(self, value)
           ^^^^^^^^^^^^^^^^^^^
TypeError: in method 'Motion_PosCommand_axis_set', argument 2 of type 'in
2025-03-14 23:57:37,609 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 49
2025-03-14 23:57:37,610 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 49, LLM Time: 31.43s
2025-03-14 23:57:37,712 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 50
2025-03-14 23:58:00,705 - Default - MainProcess - 56952 - codedata:
Program begin.
StartLinearIntplPos error code is 65556: [0x00010014] : CoreMotionApi Error: One or more axes are not in servo on state.
Elapsed_time: 2.313
----------------------

2025-03-14 23:58:00,807 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 50
2025-03-14 23:58:00,807 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 50, LLM Time: 20.58s
2025-03-14 23:58:00,910 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 51
2025-03-14 23:58:24,167 - Default - MainProcess - 56952 - codedata:
Program begin.
StartPVT error code is 65665: [0x00010081] : CoreMotionApi Error: One or more points do not have a greater time than the previous point.
Elapsed_time: 3.168
----------------------

2025-03-14 23:58:24,575 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 51
2025-03-14 23:58:24,575 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 51, LLM Time: 19.98s
2025-03-14 23:58:24,676 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 52
2025-03-14 23:58:49,200 - Default - MainProcess - 56952 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 3, in <module>
    Axes = [Axis_number_1, Axis_number_2, ...]
            ^^^^^^^^^^^^^
NameError: name 'Axis_number_1' is not defined
!!!
----------------------

2025-03-14 23:58:49,301 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 52
2025-03-14 23:58:49,301 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 52, LLM Time: 23.45s
2025-03-14 23:58:49,404 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 53
2025-03-14 23:59:08,048 - Default - MainProcess - 56952 - codeerr:
  File "\\mac\Home\Downloads\codedemo\sample.py", line 213
    Axes = [3, 6]
IndentationError: unexpected indent
!!!
----------------------

2025-03-14 23:59:08,150 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 53
2025-03-14 23:59:08,150 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 53, LLM Time: 17.75s
2025-03-14 23:59:08,251 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 54
2025-03-14 23:59:39,109 - Default - MainProcess - 56952 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 295, in <module>
    main()
  File "\\mac\Home\Downloads\codedemo\sample.py", line 230, in main
    pvti.points[i].pos = set_point_data[0]  # Position
    ~~~~~~~~~~~^^^
TypeError: 'SwigPyObject' object is not subscriptable
!!!
----------------------

2025-03-14 23:59:39,516 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 54
2025-03-14 23:59:39,516 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 54, LLM Time: 27.26s
2025-03-14 23:59:39,618 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 55
2025-03-15 00:00:12,443 - Default - MainProcess - 56952 - codedata:
Program begin.
Program End.
Elapsed_time: 2.831
----------------------

2025-03-15 00:00:12,721 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 55, LLM Time: 29.89s
2025-03-15 00:00:12,823 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 56
2025-03-15 00:00:32,131 - Default - MainProcess - 56952 - codeerr:
Traceback (most recent call last):
  File "\\mac\Home\Downloads\codedemo\sample.py", line 3, in <module>
    Axes = [Axis_number_1, Axis_number_2, ...]  # Replace with actual axis numbers
            ^^^^^^^^^^^^^
NameError: name 'Axis_number_1' is not defined
!!!
----------------------

2025-03-15 00:00:32,234 - Default - MainProcess - 56952 - DeepSeek-R1-M1 Error detected for Task ID: 56
2025-03-15 00:00:32,234 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 56, LLM Time: 18.45s
2025-03-15 00:00:32,338 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 57
2025-03-15 00:01:04,053 - Default - MainProcess - 56952 - codedata:
Program begin.
Program End.
Elapsed_time: 2.700
----------------------

2025-03-15 00:01:04,326 - Default - MainProcess - 56952 - DeepSeek-R1-M1: completed for Task ID: 57, LLM Time: 28.91s
2025-03-15 00:01:04,428 - Default - MainProcess - 56952 - DeepSeek-R1-M1: starts for Task ID: 58
